### ISSUE TITLE
9.26服务器问题反馈

### ISSUE THREAD

**Issue by Burn-Sky** [Kamikuz/Atorasumonogatarito#1]
服务器出现连接超时和连接失败，延迟过高等同类问题，请求解决。
版本号：Alpha2.0

**Comment by Kamikuz** [comment]
目前已更新客户端3.0,优化了mod与RTM追加包的加载速度。
目前最低内存要求已优化至3000MB即可！
服务器的延迟问题仍然在解决中。
具体[点我了解！](https://wiki.kamikuz.cn/#/welcome/client)
